### PR TITLE
Improved way to display books with three categories.

### PR DESCRIPTION
**Pull request by MarcPuigdemont**
There are now three ways of displaying the books, single line, grid and cards. I've also improved the search by invalidating previous searches if it hasn't finished loading.

Added a bunch of tests, also:
Screenshot 2019-03-25 at 22 35 10

### CODE REVIEW

**Comment by MarcPuigdemont** [comment]
Awaiting #3 to be merged so we have CircleCI configuration here.

**Review by mverdaguer — APPROVED** [review]
You can remove the "serve" script :)

**Review by marcmortensen — APPROVED** [review]
Nice job!

**Comment by MarcPuigdemont** [comment]
This PR should close issue #5

**Review by laurasanguesa — APPROVED** [review]

**Pull request merged**
